---
version: "3.8"

services:
  demo:
    image: sphinx_hosting_demo:latest
    user: root
    container_name: sphinx_hosting_demo
    restart: always
    hostname: sphinx_hosting_demo
    environment:
      - DEBUG=True
      - DEVELOPMENT=True
    ports:
      - "443:443"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - ../sphinx_hosting:/ve/lib/python3.10/site-packages/sphinx_hosting
      #- ../../django-theme-academy/academy_theme:/ve/lib/python3.10/site-packages/academy_theme
      #- ../../django-wildewidgets/wildewidgets:/ve/lib/python3.10/site-packages/wildewidgets
      - sphinx_hosting_demo_media:/media

  mysql:
    image: mysql:8.0.23
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    cap_add:
      # removes error messages like: mbind: Operation not permitted
      - SYS_NICE
    ports:
      - "3306:3306"
    volumes:
      - ./sql/docker/my.cnf:/etc/mysql/conf.d/dev.cnf
      - ./sql/docker:/docker-entrypoint-initdb.d
      - sphinx_hosting_demo_data:/var/lib/mysql


  elastic:
    image: elasticsearch:7.10.1
    container_name: search
    hostname: search
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1500m
    cap_add:
      - IPC_LOCK

volumes:
  # The Docker volume in which the database's files are stored. Works in tandem
  # with the "demo_data:/var/lib/mysql" volume mount defined above.
  sphinx_hosting_demo_data:
  sphinx_hosting_demo_media:
