# Generated by Django 4.1.2 on 2022-11-04 18:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import sphinx_hosting.models
import sphinx_hosting.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(help_text='The human name for this project', max_length=100, verbose_name='Project Name')),
                ('description', models.CharField(blank=True, help_text='A brief description of this project', max_length=256, null=True, validators=[sphinx_hosting.validators.NoHTMLValidator()], verbose_name='Brief Description')),
                ('machine_name', models.SlugField(help_text='Used in the URL for the project. Must be unique.', unique=True, verbose_name='Machine Name')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='A version of our project', max_length=64, verbose_name='Version')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='sphinxhostingcore.project')),
            ],
        ),
        migrations.CreateModel(
            name='SphinxPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(help_text='The path to the page under our top slug', max_length=255, verbose_name='Relative page path')),
                ('content', models.TextField(help_text='The full JSON payload for the page', verbose_name='Content')),
                ('title', models.CharField(help_text='Just the title for the page, extracted from the page JSON', max_length=255, verbose_name='Title')),
                ('body', models.TextField(blank=True, help_text='Just the body for the page, extracted from the page JSON. Some pages have no body.', verbose_name='Body')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sphinxhostingcore.version')),
            ],
            options={
                'verbose_name': 'sphinx page',
                'verbose_name_plural': 'sphinx pages',
            },
        ),
        migrations.CreateModel(
            name='SphinxImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('orig_path', models.CharField(help_text='The original path to this file in the Sphinx documentation package', max_length=256, verbose_name='Original Path')),
                ('file', models.FileField(help_text='The actual image file', upload_to=sphinx_hosting.models.sphinx_image_upload_to, verbose_name='An image file')),
                ('version', models.ForeignKey(help_text='The version of our project documentation with which this image is associated', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sphinxhostingcore.version')),
            ],
            options={
                'verbose_name': 'sphinx image',
                'verbose_name_plural': 'sphinx images',
                'unique_together': {('version', 'orig_path')},
            },
        ),
    ]
