# Generated by Django 4.1.2 on 2022-11-21 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sphinxhostingcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='sphinx_version',
            field=models.CharField(blank=True, default=None, help_text='The version of Sphinx used to documentation for this set', max_length=64, null=True, verbose_name='Sphinx Version'),
        ),
        migrations.AlterField(
            model_name='sphinxpage',
            name='version',
            field=models.ForeignKey(help_text='The Version to which this page belongs', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sphinxhostingcore.version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='project',
            field=models.ForeignKey(help_text='The Project to which this Version belong', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='sphinxhostingcore.project'),
        ),
        migrations.AlterUniqueTogether(
            name='sphinxpage',
            unique_together={('version', 'relative_path')},
        ),
    ]
