# Generated by Django 5.0.7 on 2024-07-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphinxhostingcore', '0013_projectrelatedlink_url_to_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latest_version',
            field=models.ForeignKey(help_text='The latest version of this project.  This is the version that will be shown when you click "Read Docs" on the project page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sphinxhostingcore.version'),
        ),
    ]
