# Generated by Codex on 2026-03-23.

from __future__ import annotations

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Create the demo ``SearchNote`` model used by unified-search examples.
    """

    #: Whether this is the first migration for the demo core app.
    initial = True

    #: Migrations that must run before this migration.
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("sphinxhostingcore", "0018_sphinxdocument"),
    ]

    #: Operations applied by this migration.
    operations: ClassVar[list[migrations.CreateModel]] = [
        migrations.CreateModel(
            name="SearchNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="+",
                        to="sphinxhostingcore.project",
                    ),
                ),
                (
                    "classifiers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="sphinxhostingcore.classifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "search note",
                "verbose_name_plural": "search notes",
            },
        )
    ]
