# Generated by Django 6.0.3 on 2026-03-23 21:59

from typing import Any, ClassVar

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    """
    Align the demo ``SearchNote`` schema with ``TimeStampedModel`` defaults.
    """

    #: Migrations that must run before this migration.
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0001_initial"),
    ]

    #: Operations applied by this migration.
    operations: ClassVar[list[Any]] = [
        migrations.AlterModelOptions(
            name="searchnote",
            options={
                "ordering": ("title",),
                "verbose_name": "search note",
                "verbose_name_plural": "search notes",
            },
        ),
        migrations.AlterField(
            model_name="searchnote",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="searchnote",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                verbose_name="modified",
            ),
        ),
    ]
